Binyamin/support descriptor extensions
xpodev/extypes pull request #9
Opened 2023-01-22 20:39 UTC by binyamin555

2023-01-22 20:40 UTC, binyamin555 commented
#6

2023-01-22 20:59 UTC, elazarcoh approved these changes
LGTM.
BTW we need to create a github actions for testing

2023-01-22 20:59 UTC, elazarcoh commented on src/extypes/__init__.py
> +        print("marked as extension:", o)
don't forget to remove

2023-01-22 21:01 UTC, binyamin555 commented on src/extypes/__init__.py
> +        print("marked as extension:", o)
Right.. if one of you get to do that before that would also be ok, I got off for today

2023-01-23 08:08 UTC, binyamin555 commented on src/extypes/__init__.py
> +        print("marked as extension:", o)
Done

2023-01-23 19:11 UTC, neriyaco requested changes
It looks like the `pytest` command is failing on the `test_length_function` function.
Also, add test to the descriptor extension under the tests directory.

2023-01-23 19:17 UTC, neriyaco approved these changes

2023-01-23 19:18 UTC, binyamin555 commented
> It looks like the `pytest` command is failing on the `test_length_function` function.
> Also, add test to the descriptor extension under the tests directory.

I changed it, however, I'm unable to test my changes due to platform incompatibility.

Can you review once again?

2023-01-23 19:19 UTC, merged